---
- name: install ssl cert package
  apt: pkg=ssl-cert

- name: create ssl-key group
  group: name=ssl-key state=present

- name: install ssl key
  template: src=etc/ssl/private/cuttle.key
            dest=/etc/ssl/private/{{ name|default('cuttle') }}.key
            owner=root group=ssl-key mode=0640
  when: ssl_key or bbg_ssl.key

- name: install ssl cert
  template: src=etc/ssl/certs/cuttle.crt
            dest=/etc/ssl/certs/{{ name|default('cuttle') }}.crt
  when: ssl_cert or bbg_ssl.cert

- name: install ssl intermediate cert
  template: src=etc/ssl/certs/intermediate.crt
            dest=/etc/ssl/certs/{{ name|default('cuttle') }}-intermediate.crt
  when: ssl_intermediate or bbg_ssl.intermediate

- name: install ssl ca cert
  template: src=usr/local/share/ca-certificates/ca_cert.crt
            dest=/usr/local/share/ca-certificates/{{ name|default('cuttle-ca_cert') }}.crt
  when: ssl_ca_cert or bbg_ssl.ca_cert
  notify: update ca certificates

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
